apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-golang-gin
  namespace: nsthdso
spec:
  selector:
    matchLabels:
      app: demo-golang-gin
  template:
    metadata:
      labels:
        app: demo-golang-gin
    spec:
      containers:
      - name: demo-golang-gin
        image: nsthdso.azurecr.io/golang-gin:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        env:
          - name: node
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          protocol: TCP
