info:
  contact: {}
  license:
    name: Apache 2.0
  title: Swagger Example API
  version: v0.0.1
paths:
  /cat/random:
    get:
      consumes:
      - application/json
      description: Get random cat
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get random cat
      tags:
      - cat
  /debug:
    get:
      consumes:
      - application/json
      description: Get debug information
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get debug information
      tags:
      - debug
  /users/:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all users
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get an user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get an user by ID
      tags:
      - users
swagger: "2.0"
