info:
  contact: {}
  title: Golang Gin-Gonic Example API
  version: v0.0.2
paths:
  /debug:
    get:
      consumes:
      - application/json
      description: Get debug information
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get debug information
      tags:
      - debug
  /debug/execute/{cmd}:
    get:
      consumes:
      - application/json
      description: Execute command and return result
      parameters:
      - description: Command to execute
        in: path
        name: cmd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Execute command and return result
      tags:
      - debug
  /users/:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all users
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get an user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get an user by ID
      tags:
      - users
swagger: "2.0"
