definitions:
  main.album:
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
  title: Swagger Example API
  version: v0.0.1
paths:
  /albums/:
    get:
      consumes:
      - application/json
      description: Get all albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all albums
      tags:
      - albums
    post:
      consumes:
      - application/json
      description: Create an album
      parameters:
      - description: JSON of album to create
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/main.album'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create an album
      tags:
      - albums
  /albums/{id}:
    get:
      consumes:
      - application/json
      description: Get an album by ID
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get an album by ID
      tags:
      - albums
  /debug:
    get:
      consumes:
      - application/json
      description: Get debug information
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get debug information
      tags:
      - debug
swagger: "2.0"
